/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sheenline_muis_common_TestJNI */

#ifndef _Included_com_sheenline_muis_common_TestJNI
#define _Included_com_sheenline_muis_common_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    InitXLTLib
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sheenline_muis_common_TestJNI_InitXLTLib
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    OpenDevice
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_OpenDevice
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    CloseDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_CloseDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    StartWork
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_StartWork
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    StopWork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_StopWork
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetTriggerMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetTriggerMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    setCrystaltype
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_setCrystaltype
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetDelay
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetDelay
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetDetectionType
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetDetectionType
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetGain
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetGain
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetSampleTime
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetSampleTime
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetWeldLevel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetWeldLevel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetFilter
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetFilter
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetPulseWidth
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetPulseWidth
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetFocusLaw
 * Signature: (I[[FII[[FII)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetFocusLaw
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint, jfloatArray, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    OpenDataStream
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_OpenDataStream
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    getData
 * Signature: (I[CIII[[II)I
 */
JNIEXPORT jintArray JNICALL Java_com_sheenline_muis_common_TestJNI_getData
  (JNIEnv *, jobject, jint, jcharArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    CloseDataStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_CloseDataStream
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    GetEncoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_GetEncoder
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    Alarm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_Alarm
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetTGCEnable
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetTGCEnable
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    SetTGCCurve
 * Signature: (II[D[DI)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_SetTGCCurve
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    only_startdma
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_only_1startdma
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    only_startsystem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_only_1startsystem
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    only_startut
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_only_1startut
  (JNIEnv *, jobject);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    sendPara
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_sendPara
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    sendInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_sheenline_muis_common_TestJNI_sendInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_sheenline_muis_common_TestJNI
 * Method:    DestroyXLTLib
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_sheenline_muis_common_TestJNI_DestroyXLTLib
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
